import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Get.module.css'
import {signIn, useSession} from "next-auth/react"
import Link from 'next/link'

export default function Get(props: any) {
  const {data: session} = useSession();

  async function onClickGet(){
    await fetch("/api/delete", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        id: props.id
        //and after sign and send to dbSide
      })
    })  
  }

  if (session) {
    return (
      <div className={styles.Get}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          Signed in as {session.user.email} <br />
            <div className={styles.divInfo}>
              <p>{props.address}</p>
              <p>{props.phone}</p>
            </div>
          <Link href="/get" className={styles.LinkGray} onClick={onClickGet}>get house</Link>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          </footer>
      </div>
    )
  } else {
    return (
      <div className={styles.Get}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <button onClick={()=>signIn()}>enter</button>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}

export const getServerSideProps = async () => {
  const response = await fetch(`http://localhost:3000/api/get`)

  const house = await response.json()

  return {
    props: {
      id: house.id,
      address: house.address,
      phone: house.phone
    }
  }
}