import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Get.module.css'
import {signIn, useSession} from "next-auth/react"
import Link from 'next/link'
import {useState} from 'react'

export default function Get(props: any) {
  const {data: session} = useSession()
  var [active,setActive] = useState(0)

  async function onClickGet(){
     await fetch(`/api/trans?id=${props.id}&sessionUserEmail=${session.user.email}`) 
     setActive(1)
  }

  if (session) {
    return (
      <div className={styles.Get}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.divMain}>
              <p>Signed in as <br />{session.user.email}</p> <br />
              <div className={active? styles.divInfoActive : styles.divInfo }>
                <p>{props.address}</p>
                <p>{props.phone}</p>
              </div><br />
              <Link href="/get" className={active? styles.LinkActive : styles.LinkBlue} onClick={onClickGet}>get house</Link>
          </div>
              </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          </footer>
      </div>
    )
  } else {
    return (
      <div className={styles.Get}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <div className={styles.divMain}>
          <Link href="/" onClick={()=>signIn()} className={styles.LinkWhite}>enter</Link>
        </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}

export const getServerSideProps = async () => {
  const response = await fetch(`http://localhost:3000/api/get?db=dbMain`)

  const house = await response.json()

  return {
    props: {
      id: house.id,
      address: house.address,
      phone: house.phone,
      requisites: house.requisites,
      signPut: house.signPut
    }
  }
}