import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {signIn, useSession} from "next-auth/react"
import Link from 'next/link'

export default function Home() {
  const {data: session} = useSession();

  if (session) {
    return (
      <div className={styles.Home}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.divMain}>
            <p>Signed in as <br />{session.user.email}</p> <br /><br />
            <Link href="/get" className={styles.LinkWhite}>get house</Link><br /><br /><br />
            <Link href="/put" className={styles.LinkWhite}>put house</Link><br /><br /><br />
            <Link href="/donate" className={styles.LinkGreen}>donate</Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          </footer>
      </div>
    )
  } else {
    return (
      <div className={styles.Home}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.divMain}>
            <Link href="/" onClick={()=>signIn()} className={styles.LinkWhite}>enter</Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}
