import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Put.module.css'
import {signIn, useSession} from "next-auth/react"
import Link from 'next/link'
import {useState} from 'react'

export default function Put() {
  const {data: session} = useSession();
  const [address, setAddress] = useState("");
  const [phone, setPhone] = useState("");
  const [requisites, setRequisites] = useState("");

  function onChangeAddress(event: React.ChangeEvent<HTMLInputElement>){
    setAddress(event.target.value)
  }
  function onChangePhone(event: React.ChangeEvent<HTMLInputElement>){
    setPhone(event.target.value)
  }
  function onChangeRequisites(event: React.ChangeEvent<HTMLInputElement>){
    setRequisites(event.target.value)
  }
  async function onClickPut(){
    console.log("onClickPut") 
    await fetch("/api/put", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        address: address,
        phone: phone,
        requisites: requisites,
        signPut: ""+session.user.email,
        signGet: ""
      })
    })  
  }
  
  if (session) {
    return (
      <div className={styles.Put}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          Signed in as {session.user.email} <br />
          <div className={styles.divInfo}>
            <label>address</label><br />
            <input type="text" onChange={onChangeAddress} value={address}></input><br />
            <label>phone</label><br />
            <input type="text" onChange={onChangePhone} value={phone}></input><br />
            <label>requisites</label><br />
            <input type="text" onChange={onChangeRequisites} value={requisites}></input><br />
          </div>
          <Link href="/put" className={styles.LinkGray} onClick={onClickPut}>put house</Link>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          </footer>
      </div>
    )
  } else {
    return (
      <div className={styles.Put}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <button onClick={()=>signIn()}>enter</button>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}
