import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Put.module.css'
import {signIn, useSession} from "next-auth/react"
import Link from 'next/link'
import {useState} from 'react'

export default function Put() {
  const {data: session} = useSession()
  const [address, setAddress] = useState("")
  const [phone, setPhone] = useState("")
  const [requisites, setRequisites] = useState("")
  var [active,setActive] = useState(0)

  function onChangeAddress(event: React.ChangeEvent<HTMLInputElement>){
    setAddress(event.target.value)
  }
  function onChangePhone(event: React.ChangeEvent<HTMLInputElement>){
    setPhone(event.target.value)
  }
  function onChangeRequisites(event: React.ChangeEvent<HTMLInputElement>){
    setRequisites(event.target.value)
  }
  async function onClickPut(){
    await fetch("/api/put", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        address: address,
        phone: phone,
        requisites: requisites,
        signPut: ""+session.user.email,
        signGet: ""
      })
    })  
    setActive(1)
    setTimeout(()=>{
      setActive(0)
    },"500")
  }
  
  if (session) {
    return (
      <div className={styles.Put}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.divMain}>
            <p>Signed in as <br />{session.user.email}</p> <br />
            <div className={active? styles.divInfoActive : styles.divInfo}>
              <label>address</label><br />
              <input type="text" onChange={onChangeAddress} value={address}></input><br />
              <label>phone</label><br />
              <input type="text" onChange={onChangePhone} value={phone}></input><br />
              <label>requisites</label><br />
              <input type="text" onChange={onChangeRequisites} value={requisites}></input><br /><br />
            </div><br />
            <Link href="/put" className={active? styles.LinkActive : styles.LinkBlue} onClick={onClickPut}>put house</Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          </footer>
      </div>
    )
  } else {
    return (
      <div className={styles.Put}>
        <Head>
          <title>donationhouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.divMain}>
            <Link href="/" onClick={()=>signIn()} className={styles.LinkWhite}>enter</Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://github.com/bazylevnik0"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by bazylevnik0 for Hack the Bronx 2
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}
