import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.Home}>
      <Head>
        <title>donationhouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/bazylevnik0"
          target="_blank"
          rel="noopener noreferrer"
        >
          created by bazylevnik0 for Hack the Bronx 2
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
